# Preprocessing

This notebook cleans the Online Retail dataset and saves a reusable processed file.

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve().parent   # if notebook is inside notebooks/
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.data_loader import load_retail_data
from src.preprocess import clean_retail_data

In [2]:
from pathlib import Path
import pandas as pd
from src.data_loader import load_retail_data
from src.preprocess import clean_retail_data

In [3]:
DATA_DIR = Path('../data/raw')
OUT_DIR = Path('../data/processed')
OUT_DIR.mkdir(parents=True, exist_ok=True)
candidate_files = list(DATA_DIR.glob('*.xlsx')) + list(DATA_DIR.glob('*.xls')) + list(DATA_DIR.glob('*.csv'))
if not candidate_files:
    raise FileNotFoundError('No raw dataset found in ../data/raw/.')
raw = load_retail_data(candidate_files[0])
raw.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
clean = clean_retail_data(raw)
print('Raw rows:', len(raw))
print('Clean rows:', len(clean))
print('Removed rows:', len(raw) - len(clean))
clean.head()

Raw rows: 541909
Clean rows: 397884
Removed rows: 144025

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesLineTotal
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [5]:
out_path = OUT_DIR / 'online_retail_clean.csv'
clean.to_csv(out_path, index=False)
out_path

WindowsPath('../data/processed/online_retail_clean.csv')

In [6]:
clean.describe(include='all').T.head(20)

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
InvoiceNo,397884,18532,576339,542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockCode,397884,3665,85123A,2035,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,397884,3877,WHITE HANGING HEART T-LIGHT HOLDER,2028,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,397884.0,NaN,NaN,NaN,12.988238,1.0,2.0,6.0,12.0,80995.0,179.331775
InvoiceDate,397884,NaN,NaN,NaN,2011-07-10 23:41:23.511023,2010-12-01 08:26:00,2011-04-07 11:12:00,2011-07-31 14:39:00,2011-10-20 14:33:00,2011-12-09 12:50:00,NaN
UnitPrice,397884.0,NaN,NaN,NaN,3.116488,0.001,1.25,1.95,3.75,8142.75,22.097877
CustomerID,397884,4338,17841.0,7847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,397884,37,United Kingdom,354321,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalesLineTotal,397884.0,NaN,NaN,NaN,22.397,0.001,4.68,11.8,19.8,168469.6,309.071041

## Output

The cleaned file saved here will be reused by the segmentation, cohort, and basket notebooks.